version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/renderer'
    schedule:
      interval: 'weekly'
  - directory: /
    schedule:
      interval: 'weekly'
    package-ecosystem: 'gradle'
