[package]
name = "wasm-mrml-renderer"
version = "0.0.1"
edition = "2024"

[dependencies]
mrml = { version = "5", features = ["local-loader"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
tempfile = "3.8"

[lib]
crate-type = ["cdylib"]
